version: '3'
services:
  web:
    container_name: web
    build: .
    command: uvicorn src.main:app --host 0.0.0.0 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
    env_file:
      - .env
    ports:
      - "27017:27017"
  rabbit:
    container_name: rabbit
    image: rabbitmq:3-management
    env_file:
      - .env
    ports:
      - 5672:5672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  celery_worker:
    restart: always
    container_name: celery_worker
    build: .
    command: sh ./entrypoint_celery.sh
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - rabbit
  redis:
    restart: unless-stopped
    image: redis:7.0.5-alpine
    expose:
      - '6379:6379'
    env_file:
      - .env
volumes:
  mongodb_data:
  rabbitmq_data: